<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\AutorizacaoAutenticacao.Application\AutorizacaoAutenticacao.Application.csproj" />
    <ProjectReference Include="..\AutorizacaoAutenticacao.Infrastructure\AutorizacaoAutenticacao.Infrastructure.csproj" />
  </ItemGroup>

</Project>
